### ISSUE TITLE
Zielgruppenanalyse einfügen

### ISSUE THREAD

**Issue by sebulino** [sebulino/Strategie#1]
Kapitel mit Zielgruppenanalyse einfügen
(Martin Schütz, Sebastian Alscher: Piratennahe Milieus, 2016)

**Comment by Annnnette** [comment]
bei Zielgruppen gibt es große Unterschiede: 
- Leute, ein Verantwortungsgefühl entwickeln, und daraus eine Motivation, sich zu engagieren
- Leute, bei denen man mit unseren Kernthemen offene Türen einrennt 
- Leute, die uns früher mal gewählt haben aber uns jetzt nicht mehr viel zutrauen (weil wir unter 5 % bleiben, weil wir zu wenig sichtbar sind, weil wir uns (angeblich) dauernd streiten...
- bei Kommunalwahlen Leute, die ein Anliegen haben und sich evtl. durch unseren Kommunalvertreter bestärkt sehen

**Comment by sebulino** [comment]
Wir hatten 2016 bereits eine Zielgruppenanalyse durchgeführt, die hab ich nun eingefügt.
