### ISSUE TITLE
Betonung der Themenkompetenz durch Veranstaltungen: 42eV

### ISSUE THREAD

**Issue by Annnnette** [sebulino/Strategie#13]
Es ist zu überlegen, solche Tagungen und Veranstaltungen in Kooperation mit 42eV durchzuführen.

**Comment by sebulino** [comment]
Ja, das wissen um den 42 bzw was sie machen können oder in der Vergangenheit auch schon gemacht haben, sollte besser durch die Partei durchsickern. das ist aber auch Aufgabe des 42. 
Hierfür wäre es vermutlich eine gute Idee, wenn sie regelmäßig in der PolGef-Runde Bescheid geben? 
Ich werde das dem 42 nochmal zurufen, ansonsten sehe ich nicht, wie das in das Strategiepapier für den BuVo passen könnte.

**Comment by Annnnette** [comment]
ich sehe den 42 beim Stammtisch, dann rufe ich auch noch mal
