### ISSUE TITLE
Problemfeld Abhängigkeit von Einzelpersonen

### ISSUE THREAD

**Issue by Annnnette** [sebulino/Strategie#14]
Es gibt mehrere Gründe für die "Flaschenhälse":
- wir sind zu wenig Leute
- leider bauen sich immer mehr bürokratische Hürden ein, manche Funktionsträger haben zu wenig Vertrauen in andere und Delegieren nicht, bzw. entmutigen Eigeninitiativen
- Basispiraten wissen oft nicht recht, wie sie sich einbringen sollen und werden zu wenig ermutigt. Es gibt viele, die was zu sagen haben, aber sich darauf beschränken, das nur in Chats oder im Forum auszutoben. Oft in wenig zielführender Weise (übrigens wie früher die Mailinglisten der AGs, die gingen of hin und her im Kreis, ohne, dass sich etwas kondensiert hätte. Wir müssen sie gezielt motivieren, zB., indem man sie Blogbeiträge schreiben lässt.
- Blogbeiträge sind sichtbare Aktivitäten nach außen, die gerade für Interessenten interessant sein können. Sie müssen nicht genau die Meinung der Partei widerspiegeln, eine ungefähre Nähe reicht, denn der, der sie schreibt, ist persönlich verantwortlich. Wir sollten viel mehr Blogbeiträge, nicht nur auf der Bundesseite, sondern auch auf den Landes- und KV-Seiten einwerben. Dazu sollten wir Diskussionen beobachten, und Diskussionsteilnehmer gezielt auffordern und motivieren, einen Blog zu schreiben. Dabei ist es wichtig, mit redaktioneller Arbeit zu einer guten Qualtiät zu verhelfen, man sollte es allerdings vermeiden, zu viele bürokratische Hindernisse bis zur Genehmigung einzubauen. Viele sind nicht geübt im Schreiben, da bietet sich eine gemeinsame Autorenschaft an.

**Comment by sebulino** [comment]
Eigentlich geht es hier nicht darum, die Todos inhaltlich zu diskutieren oder zu lösen, sonder eher darum, neue Themen zu ergänzen (in dem Fall wäre es natürlich sinnvoll zu begründen, warum etwas aufgenommen werden sollte), oder inhaltlich falsch erscheinende Dinge zu korrigieren. Die Lösung der Probleme oder das Abarbeiten der Todos ist dann ein eigener Schritt, für den man sich die Zeit und Ressourcen nehmen sollte das stringent durchzuziehen. Die Aufgabe das zu organisieren liegt dann in dem Fall der genannten Todos beim Bundesvorstand.

Daher würde ich das hier schließen, weil das Problem bekannt ist. :)
