### ISSUE TITLE
Problemfeld Attraktivität für jüngere Menschen

### ISSUE THREAD

**Issue by Annnnette** [sebulino/Strategie#15]
Wichtig wäre es, den Kontakt zu jüngeren Menschen zu suchen und herauszufinden, warum sie uns früher gewählt haben und jetzt nicht mehr. Also dahin gehen, wo sie sind und mit ihnen ins Gespräch kommen.

**Comment by sebulino** [comment]
Danke für die Anmerkung!
Hier geht es eher darum, die Aufgaben zu erfassen, von denen man die Notwendigkeit sieht, sie zu behandeln. Das "Abarbeiten" selbst passiert dann in der dafür angestoßenen Maßnahme oder Gruppe oder Form, die dafür gefunden wird. 
Für eine allgemeine Diskussion würde sich dann das Forum beispielsweise eignen.
