### ISSUE TITLE
Problemfeld Darstellung politischer Positionen

### ISSUE THREAD

**Issue by Annnnette** [sebulino/Strategie#16]
Wie weit funktionieren AGs noch? Haben sie genug Leute? Wie arbeiten sie? Sind sie mehr als nur ein Themendiskussionsforum (so habe ich das früher mal in der AG Außenpolitik erlebt). Wie strukturieren sie ihre Arbeit? Wie motiviert man Neue, mitzuarbeiten, wie behält die AG den Überblick über bereits erreichte Konsense, Dissense, Ideen, usw? Wie verhindert sie, dass Diskussionen immer wieder von vorne anfangen? Wie läuft die Kommunikation nach außen? Durch Anträge auf Parteitagen? Direkt mit Vorständen? Mit der Pressegruppe?
Beim Weiterlesen sehe ich, dass das Thema AGs auch im Punkt "Problemfeld politische Arbeit" angesprochen wird. Dort wird es - zu Recht - aus der Sicht von Vorstandsarbeit und Satzungsänderungen diskutiert. Was noch fehlt, ist eine Vorstellung, wie die AGS arbeiten, siehe Fragen oben. Soll das jede AG selbst organisieren? Oder wäre es nicht besser, wenn man da Vorschläge für Strukturen hätte?
Die AGs sind damals auch kaputt gegangen, weil die Arbeit chaotisch war, bis zu 1000 Mails am Tag, Themensprünge noch und noch, Wiederholung von Diskussionen, keine Zusammenfasung, keine Entwicklung, zum Schluss waren viele genervt, ich auch.

**Comment by sebulino** [comment]
An sich ist die Arbeit (und auch Gründung) der AGs frei und nichts, worauf der Bundesvorstand Einfluss nehmen könnte, sofern das als gute Idee gesehen würde. Aber Aufgabe des Bundesvorstand ist es schon dafür zu sorgen, Mitglieder zur Mitarbeit zu motivieren und den Rahmen dafür zu schaffen.
Weil einiges an davon auch hier angesprochen würde, fasse ich das in dem anderen Issue zusammen, Issue #7 - AGs - Fehlende Leitlinien und fehlende Sichtbarkeit.
