### ISSUE TITLE
Wählergruppe 65 plus

### ISSUE THREAD

**Issue by TanFoxley** [sebulino/Strategie#3]
Diese Wählergruppe ist enorm wichtig, viel Wissen aufgrund des Alters und viel Zeit (meistens)
https://www.tagblatt.ch/leben/philosoph-die-alten-muessen-sich-den-respekt-verdienen-ld.1143534?utm_source=pocket-newtab

**Comment by Annnnette** [comment]
ja, diese Wählergruppe war früher oder ist immer noch aktiv. Die waren jung, als sich die Grünen gegründet haben. Damals standen die Grünen für Basisidemokratie und individuelle Freiheit, jetzt ist das kein Thema mehr, siehe Polizeigesetze, an denen sie beteiligt sind. Da kann man die abholen

**Comment by sebulino** [comment]
Es fällt mir schwer, die Zielgruppen alleine anhand des Alters zu bestimmen. Aber hierzu habe ich die Zielgruppenanalyse von damals nun in den Text auch eingefügt, die darauf Bezug nimmt (siehe Issue #1). Daher würde ich dieses Issue schließen. 

Wenn ihr aber sagt, dass die Analyse da noch unzureichend ist, dann sollten wir da vermutlich eine neue Analyse anstoßen. Bitte macht dann ein neues Issue auf, damit wir das angehen können.
